/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/healthy-cow.glb --transform --output src/components/models/HealthyCow.tsx 
Files: public/models/healthy-cow.glb [111KB] > /home/phantomojo/HACKATHON/mali-connect-app/src/components/models/healthy-cow-transformed.glb [13.87KB] (88%)
Author: Didier Hannoir (https://sketchfab.com/dhannoir)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cow-neutral-pose-aea6aec8741a424385ca378389feb73b
Title: Low-poly cow - neutral pose
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    vache_0: THREE.Mesh
    vache_1: THREE.Mesh
    vache_2: THREE.Mesh
    vache_3: THREE.Mesh
    vache_4: THREE.Mesh
    vache_5: THREE.Mesh
  }
  materials: {
    blanc: THREE.MeshStandardMaterial
    rose: THREE.MeshStandardMaterial
    noir: THREE.MeshStandardMaterial
    blanc_sale: THREE.MeshStandardMaterial
    sabots: THREE.MeshStandardMaterial
    taches: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/models/low-poly_cow_-_neutral_pose.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vache_0.geometry} material={materials.blanc} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vache_1.geometry} material={materials.rose} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vache_2.geometry} material={materials.noir} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vache_3.geometry} material={materials.blanc_sale} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vache_4.geometry} material={materials.sabots} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vache_5.geometry} material={materials.taches} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/low-poly_cow_-_neutral_pose.glb')
